services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - uploads_data:/app/uploads
    environment:
      NODE_ENV: production
      PORT: 3000
      FRONTEND_URL: https://platformaapp.ru
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      SMTP_HOST: mail.hosting.reg.ru
      SMTP_PORT: "465"
      SMTP_SECURE: "true"
      SMTP_USER: platformaapp@platformaapp.ru
      SMTP_PASS: 8QLq8vVu4iVi7bn
      YOOKASSA_SHOP_ID: ${YOOKASSA_SHOP_ID}
      YOOKASSA_SECRET_KEY: ${YOOKASSA_SECRET_KEY}
      YOOKASSA_BASE_URL: ${YOOKASSA_BASE_URL:-https://api.yookassa.ru/v3}
      YOOKASSA_WEBHOOK_URL: ${YOOKASSA_WEBHOOK_URL}
      MY_OWN_CONF_API_KEY: ${MY_OWN_CONF_API_KEY}
    restart: unless-stopped

volumes:
  uploads_data:
